# Generated by Django 3.2.3 on 2021-05-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_public',
        ),
    ]
