# Generated by Django 3.2.3 on 2021-05-21 21:30

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_pictures3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=main_app.models.make_unique_picture_filename),
        ),
        migrations.DeleteModel(
            name='PictureS3',
        ),
    ]
